# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_manage', '0002_auto_20170910_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品分类')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='商品价格')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manage.Category', verbose_name='商品分类')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=20, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='nickname', max_length=40, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_manage.User', verbose_name='用户'),
        ),
    ]
