# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manage', '0003_auto_20170914_2240'),
        ('product_manage', '0003_product'),
    ]

    operations = [
    ]
